language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python app.py
deploy:
  provider: heroku
  api_key:
    secure: Q049RHKNEBGP6qdX5u2qDjsAe692rVb2X3+7oZSbATcVkNPCTQWMs0kW+o8CI4impcIfJ099QWFFuW3Qmp1xmDrWy4XNhMmEmo4DdbmASVv3GNWtehl0B1nrIImSLtgdFjGXH4agFslGHaaqlEyC3cljfUBWatlyEVnLkkxPY+CSwbFwAMV1/iwKKstDY3u7dLaIHnzRJcVUaNfHwjs2j6ABH6lBIVfa7UFTMKHcxIn2yFWKnsPUwOB396HW6bx4aClafrb0d0H5rP2b+VCLe3Iri7lBixRvNXzuvNtM/FuJWaD2rj758j0rtch81NTaf/pUg9WPoQcvnDlhHUOJqg5EtajrqGIInNwpJQKK/xQN1VQLvlPUYo1DbaNGHJgB0RKvG2DMhABBQsi52NJGUcgYCsDzHO8THkt3KvasGNnd811oJNoi54z4RoYEdRX/DchyA8qXwTDe+twR6wBkyifS4ANvdOHIBJyKgqZEKqiCzSCM14Z7rr92usaqvCs3CCmdyUo5Xu5MqZ4ADgcjsqxeSWhqVdl4HSR0LwISuQ1LumyzTh6hxClGk7/aHhgjaJ21xDg2KgQJOb3WyoGSpI6I1D1d7Wsx4T0nn0gLw0QwslqiWtJKWoWc5lduD5iaPKMgZs4iLpz9jvpjOY0cdog2Y1S4mGoFDGMWLdrnHZk=
  app: 'no'
  on:
    repo: elayoktan/facebook_bot


