language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: b843f694-3742-4285-8a23-862279d15af9
  app: nereye
  on:
    elayoktan/facebook_bot


